spring:
  application:
    name: taskflow-java-spring-keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: taskflow
            client-secret: <CLIENT_KEY>
            client-name: taskflow
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/taskflow

server:
  port: 8091
